// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: led_test_light

#ifndef _UI_COMP_LABEL3_H
#define _UI_COMP_LABEL3_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Label3
#define UI_COMP_LABEL3_LABEL3 0
#define _UI_COMP_LABEL3_NUM 1
lv_obj_t * ui_Label3_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
