// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: led_test_light

#include "../ui.h"

void ui_comp_Label3_create_hook(lv_obj_t * comp)
{
}
