// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: led_test_light

#include "../ui.h"


// COMPONENT Label3

lv_obj_t * ui_Label3_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Label3;
    cui_Label3 = lv_label_create(comp_parent);
    lv_obj_set_height(cui_Label3, 20);
    lv_obj_set_width(cui_Label3, lv_pct(100));
    lv_obj_set_x(cui_Label3, 1);
    lv_obj_set_y(cui_Label3, -8);
    lv_obj_set_align(cui_Label3, LV_ALIGN_CENTER);
    lv_label_set_long_mode(cui_Label3, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(cui_Label3, "连接中");
    lv_obj_set_style_text_align(cui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label3, &ui_font_WSChinese16ALL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_LABEL3_NUM);
    children[UI_COMP_LABEL3_LABEL3] = cui_Label3;
    lv_obj_add_event_cb(cui_Label3, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Label3, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Label3_create_hook(cui_Label3);
    return cui_Label3;
}

