// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: led_test_light

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label5, lv_pct(100));
    lv_obj_set_height(ui_Label5, lv_pct(100));
    lv_obj_set_x(ui_Label5, 1);
    lv_obj_set_y(ui_Label5, -1);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label5, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label5, "");
    lv_label_set_recolor(ui_Label5, "true");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_WSChinese32ALL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
