// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: led_test_light

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void config_screen_load();
void main_screen_load();
void screen_setup();

void disp_msg(const char *msg, uint8_t source);

void change_large_text_screen1(char *text);

uint8_t get_disp_chat_id();
void set_disp_chat_id(uint8_t chat_id, uint8_t source);

void get_chat_data(uint8_t index, char* data);
void set_chat_data(uint8_t index, const char* data, uint8_t source);

uint32_t get_color(uint8_t index);
void set_color(uint8_t index, uint32_t color_value, uint8_t source);

uint16_t get_speed(uint8_t index);
void set_speed(uint8_t index, uint16_t speed_value, uint8_t source);

bool get_g4_enable();
void set_g4_enable(bool enable, uint8_t source);

bool get_IR_enable();
void set_IR_enable(bool enable, uint8_t source);

bool get_hiden_enable();
void set_hiden_enable(bool enable, uint8_t source);

void write_log(uint8_t data, uint8_t source);
uint8_t read_log(uint16_t index);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
